### ISSUE TITLE
DMP load_firmware fails

### ISSUE THREAD

**Issue by mariusknaust** [copterust/mpu9250#22]
I’ve tried the newly merged DMP feature by @tchamelot with my mpu9250 connected via SPI to a STM32F1, but the load_firmware function fails verifying the written data. Is there any prerequisite using it? 

https://github.com/copterust/mpu9250/blob/8b9390891cadb94132b9e01caf99b75dc7b99e0f/src/lib.rs#L972-L974

**Comment by tchamelot** [comment]
Fixed with #24
