### ISSUE TITLE
How to read measurements triggered by interrupt pin?

### ISSUE THREAD

**Issue by pftbest** [copterust/mpu9250#34]
Hello,

Is there any example how to set up interrupt pin for a certain frequency (for example 250 Hz) and then read the imu values each time when irq pin goes low?

I think it is important to read accelerometer and gyroscope values at a steady rate so later they can be integrated.

**Comment by little-arhat** [comment]
Hello @pftbest!

You can use [RTIC](https://github.com/rtic-rs/) (formerly RTFM) to setup interrupt handler like [this](https://github.com/copterust/proving-ground/tree/master/mpu_int).

Refer to mpu configuration for frequency configuration.

**Comment by pftbest** [comment]
Thank you, this is exactly what I needed.
