### ISSUE TITLE
the trait bound `u16: cast::From<_>` is not satisfied

### ISSUE THREAD

**Issue by mwbryant** [copterust/mpu9250#39]
Sorry if this is a beginner question but I'm just starting with Rust embedded.  I am attempting to use this crate with an arduino UNO.

When I add mpu9250 as a dependency to my toml the project fails to compile with 57 errors in the form:
```

error[E0277]: the trait bound `u16: cast::From<_>` is not satisfied
    --> /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/mpu9250-0.24.2/src/lib.rs:1810:44
     |
1810 |          ((u16(buffer[offset + 6]) << 8) + u16(buffer[offset + 5])) as i16]
     |                                            ^^^^^^^^^^^^^^^^^^^^^^^ the trait `cast::From<_>` is not implemented for `u16`
     |
     = help: the trait `cast::From<f64>` is implemented for `f32`

```

I am able to compile the crate when I clone it from git.

I'm following this blog: https://blog.logrocket.com/complete-guide-running-rust-arduino/ which uses the github template: https://github.com/Rahix/avr-hal-template and all I have changed from the template is adding this dependency.

**Comment by little-arhat** [comment]
Error comes from [cast crate](https://crates.io/crates/cast) we use to perform safe conversions. 
`cast` itself generates functions/implementations based on the `target_pointer_width`: https://github.com/japaric/cast.rs/blob/main/src/lib.rs#L355. 

I don't know much about arduino uno, but [seems](https://internals.rust-lang.org/t/adding-16-bit-pointer-support/2484) it has 16bit pointers, so `cast` crate doesn't generate required functions %( 

We need to fix this in `mpu9250`, perhaps by not using `cast` at all, and doing conversions by hand. 

Thanks for reporting, will provide new version shortly!

**Comment by little-arhat** [comment]
@mwbryant please try `0.25.0`!

**Comment by mwbryant** [comment]
Works great!  Thank you so much!
